version: "3"
services:
  redis:
    image: redis
    ports:
      - 6379:6379
  kafka:
    image: blacktop/kafka:3.0.0
    ports:
      - 9092:9092
    environment:
      - KAFKA_ADVERTISED_HOST_NAME=192.168.209.36
  kafka-ui:
    container_name: kafka-ui
    depends_on:
      - kafka
    image: obsidiandynamics/kafdrop
    ports:
      - 9000:9000
    environment:
      - KAFKA_BROKERCONNECT=192.168.209.36:9092
      - JVM_OPTS=-Xms32M -Xmx64M
      - SERVER_SERVLET_CONTEXTPATH=/